#!/usr/bin/env node
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import readline from "node:readline/promises";

const generatedMarker = "Generated by copilot-cli-cost installer v1";
const requiredExperimentalFlags = ["EXTENSIONS", "STATUS_LINE"];

main().catch((error) => {
  console.error(`configure-install: ${error.message}`);
  process.exitCode = 1;
});

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const copilotHome = args.copilotHome ?? path.join(os.homedir(), ".copilot");
  const settingsPath = args.settingsPath ?? path.join(copilotHome, "settings.json");
  const launcherDirectory = args.launcherDirectory ?? path.join(copilotHome, "copilot-cli-cost");
  const prompt = createPrompter(args);

  const { settings, existed, jsonc } = readSettings(settingsPath);
  let settingsChanged = false;

  const launcherPath = await ensureStatusLineLauncher(args.platform, launcherDirectory, prompt, copilotHome);
  const statusLineCommand = launcherPath ? makeStatusLineCommand(args.platform, launcherPath) : undefined;

  settingsChanged = await enableExperimentalSettings(settings, prompt) || settingsChanged;
  settingsChanged = await enableCustomFooter(settings, prompt) || settingsChanged;

  if (!args.skipStatusLine && statusLineCommand) {
    settingsChanged = await configureStatusLine(settings, {
      launcherDirectory,
      platform: args.platform,
      prompt,
      statusLineCommand
    }) || settingsChanged;
  } else if (args.skipStatusLine) {
    console.log("Skipped status line configuration.");
  } else {
    console.log("Skipped status line configuration because the launcher could not be installed.");
  }

  if (!settingsChanged) {
    console.log("Copilot settings already contain the requested Copilot Cost configuration.");
    return;
  }

  if (jsonc) {
    const canNormalize = await prompt.confirm(
      `${settingsPath} contains comments or trailing commas. Writing changes will save it as standard JSON after creating a backup.`,
      { assumeYes: true, defaultValue: false, nonInteractive: false }
    );
    if (!canNormalize) {
      console.log("Skipped writing Copilot settings. Re-run interactively to approve JSON normalization.");
      return;
    }
  }

  writeSettings(settingsPath, settings, existed);
  console.log(`Updated Copilot settings at ${settingsPath}`);
}

function parseArgs(argv) {
  const args = {
    platform: process.platform === "win32" ? "windows" : "posix",
    skipStatusLine: false,
    yes: false
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    switch (arg) {
      case "--launcher-directory":
        args.launcherDirectory = readValue(argv, ++index, arg);
        break;
      case "--copilot-home":
        args.copilotHome = path.resolve(readValue(argv, ++index, arg));
        break;
      case "--platform":
        args.platform = readValue(argv, ++index, arg);
        break;
      case "--settings-path":
        args.settingsPath = readValue(argv, ++index, arg);
        break;
      case "--skip-statusline":
        args.skipStatusLine = true;
        break;
      case "--yes":
        args.yes = true;
        break;
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }

  if (args.platform !== "windows" && args.platform !== "posix") {
    throw new Error("--platform must be either 'windows' or 'posix'.");
  }

  return args;
}

function readValue(argv, index, flag) {
  const value = argv[index];
  if (!value) {
    throw new Error(`${flag} requires a value.`);
  }
  return value;
}

function readSettings(settingsPath) {
  if (!fs.existsSync(settingsPath)) {
    return { existed: false, jsonc: false, settings: {} };
  }

  const raw = fs.readFileSync(settingsPath, "utf8");
  if (!raw.trim()) {
    return { existed: true, jsonc: false, settings: {} };
  }

  try {
    return { existed: true, jsonc: false, settings: JSON.parse(raw) };
  } catch (jsonError) {
    const stripped = stripJsonC(raw);
    try {
      return { existed: true, jsonc: stripped.changed, settings: JSON.parse(stripped.text) };
    } catch {
      throw new Error(`Could not parse ${settingsPath}: ${jsonError.message}`);
    }
  }
}

function stripJsonC(input) {
  const withoutComments = stripComments(input);
  const withoutTrailingCommas = stripTrailingCommas(withoutComments.text);
  return {
    changed: withoutComments.changed || withoutTrailingCommas.changed,
    text: withoutTrailingCommas.text
  };
}

function stripComments(input) {
  let output = "";
  let changed = false;
  let inString = false;
  let inLineComment = false;
  let inBlockComment = false;
  let escaped = false;

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index];
    const next = input[index + 1];

    if (inLineComment) {
      if (char === "\n" || char === "\r") {
        inLineComment = false;
        output += char;
      } else {
        changed = true;
      }
      continue;
    }

    if (inBlockComment) {
      if (char === "*" && next === "/") {
        inBlockComment = false;
        index += 1;
      } else if (char === "\n" || char === "\r") {
        output += char;
      }
      changed = true;
      continue;
    }

    if (inString) {
      output += char;
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
      output += char;
    } else if (char === "/" && next === "/") {
      inLineComment = true;
      changed = true;
      index += 1;
    } else if (char === "/" && next === "*") {
      inBlockComment = true;
      changed = true;
      index += 1;
    } else {
      output += char;
    }
  }

  return { changed, text: output };
}

function stripTrailingCommas(input) {
  let output = "";
  let changed = false;
  let inString = false;
  let escaped = false;

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index];

    if (inString) {
      output += char;
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
      output += char;
      continue;
    }

    if (char === ",") {
      let nextIndex = index + 1;
      while (/\s/.test(input[nextIndex] ?? "")) {
        nextIndex += 1;
      }
      if (input[nextIndex] === "}" || input[nextIndex] === "]") {
        changed = true;
        continue;
      }
    }

    output += char;
  }

  return { changed, text: output };
}

async function ensureStatusLineLauncher(platform, launcherDirectory, prompt, copilotHome) {
  if (fs.existsSync(launcherDirectory) && !fs.statSync(launcherDirectory).isDirectory()) {
    const replace = await prompt.confirm(
      `${launcherDirectory} exists but is not a directory. Replace it with a directory for Copilot Cost launchers?`,
      { assumeYes: true, defaultValue: false, nonInteractive: false }
    );
    if (!replace) {
      return undefined;
    }
    fs.rmSync(launcherDirectory, { force: true });
  }

  fs.mkdirSync(launcherDirectory, { recursive: true });

  const launcherPath = path.join(launcherDirectory, platform === "windows" ? "statusline.cmd" : "statusline.sh");
  const content = platform === "windows" ? windowsLauncherContent(copilotHome) : posixLauncherContent(copilotHome);
  const available = await writeGeneratedFile(launcherPath, content, prompt, platform === "posix");
  return available ? launcherPath : undefined;
}

function windowsLauncherContent(copilotHome) {
  const installedPluginsDirectory = path.join(copilotHome, "installed-plugins");
  return `@echo off
rem ${generatedMarker}
setlocal EnableExtensions
set "installedRoot=${escapeBatchSetValue(installedPluginsDirectory)}"
if not exist "%installedRoot%" exit /b 0
set "statusline="
for /f "delims=" %%F in ('where /r "%installedRoot%" statusline.cmd 2^>nul ^| sort') do (
  echo(%%F | findstr /i "copilot-cli-cost.*\\\\scripts\\\\statusline.cmd$" >nul
  if not errorlevel 1 (
    set "statusline=%%F"
    goto run
  )
)
:run
if not defined statusline exit /b 0
call "%statusline%" %*
`;
}

function posixLauncherContent(copilotHome) {
  const installedPluginsDirectory = path.join(copilotHome, "installed-plugins");
  return `#!/usr/bin/env sh
# ${generatedMarker}
installed_root=${singleQuote(installedPluginsDirectory)}
if [ ! -d "$installed_root" ]; then
  exit 0
fi
statusline="$(find "$installed_root" -type f -path '*copilot-cli-cost*/scripts/statusline.sh' 2>/dev/null | sort | head -n 1)"
if [ -z "$statusline" ]; then
  exit 0
fi
exec sh "$statusline" "$@"
`;
}

async function writeGeneratedFile(filePath, content, prompt, executable) {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, "utf8");
    if (existing === content) {
      return true;
    }
    if (!existing.includes(generatedMarker)) {
      const replace = await prompt.confirm(
        `${filePath} already exists and was not generated by Copilot Cost. Replace it?`,
        { assumeYes: true, defaultValue: false, nonInteractive: false }
      );
      if (!replace) {
        console.log(`Skipped replacing ${filePath}.`);
        return false;
      }
    }
  }

  fs.writeFileSync(filePath, content, { mode: executable ? 0o755 : 0o644 });
  if (executable) {
    fs.chmodSync(filePath, 0o755);
  }
  return true;
}

async function enableExperimentalSettings(settings, prompt) {
  let changed = false;

  if (settings.experimental === undefined) {
    settings.experimental = true;
    changed = true;
  } else if (settings.experimental === false) {
    const enable = await prompt.confirm(
      "Copilot experimental features are explicitly disabled. Enable them for extensions and status line support?",
      { assumeYes: true, defaultValue: false, nonInteractive: false }
    );
    if (enable) {
      settings.experimental = true;
      changed = true;
    }
  } else if (settings.experimental !== true) {
    const replace = await prompt.confirm(
      "settings.experimental is not a boolean. Replace it with true?",
      { assumeYes: true, defaultValue: false, nonInteractive: false }
    );
    if (replace) {
      settings.experimental = true;
      changed = true;
    }
  }

  if (settings.experimental_flags === undefined) {
    settings.experimental_flags = [...requiredExperimentalFlags];
    return true;
  }

  if (!Array.isArray(settings.experimental_flags)) {
    const replace = await prompt.confirm(
      "settings.experimental_flags is not an array. Replace it with the Copilot Cost experimental flags?",
      { assumeYes: true, defaultValue: false, nonInteractive: false }
    );
    if (!replace) {
      return changed;
    }
    settings.experimental_flags = [];
    changed = true;
  }

  for (const flag of requiredExperimentalFlags) {
    if (!settings.experimental_flags.includes(flag)) {
      settings.experimental_flags.push(flag);
      changed = true;
    }
  }

  return changed;
}

async function enableCustomFooter(settings, prompt) {
  if (settings.footer === undefined) {
    settings.footer = { showCustom: true };
    return true;
  }

  if (!isPlainObject(settings.footer)) {
    const replace = await prompt.confirm(
      "settings.footer is not an object. Replace it so the custom status line can be shown?",
      { assumeYes: true, defaultValue: false, nonInteractive: false }
    );
    if (!replace) {
      return false;
    }
    settings.footer = { showCustom: true };
    return true;
  }

  if (settings.footer.showCustom !== true) {
    settings.footer.showCustom = true;
    return true;
  }

  return false;
}

async function configureStatusLine(settings, options) {
  const existingStatusLine = settings.statusLine;

  if (existingStatusLine === undefined || existingStatusLine === null) {
    settings.statusLine = { type: "command", command: options.statusLineCommand };
    return true;
  }

  if (!isPlainObject(existingStatusLine)) {
    const replace = await options.prompt.confirm(
      "settings.statusLine exists but is not an object. Replace it with the Copilot Cost status line?",
      { assumeYes: true, defaultValue: false, nonInteractive: false }
    );
    if (!replace) {
      console.log("Skipped status line configuration.");
      return false;
    }
    settings.statusLine = { type: "command", command: options.statusLineCommand };
    return true;
  }

  const currentCommand = typeof existingStatusLine.command === "string" ? existingStatusLine.command : undefined;
  if (currentCommand && isCopilotCostStatusLine(currentCommand)) {
    if (currentCommand === options.statusLineCommand || /decorator|passthrough/i.test(currentCommand)) {
      return false;
    }
    settings.statusLine = { ...existingStatusLine, type: "command", command: options.statusLineCommand };
    return true;
  }

  if (!currentCommand) {
    const replace = await options.prompt.confirm(
      "settings.statusLine does not contain a command. Replace it with the Copilot Cost status line?",
      { assumeYes: true, defaultValue: false, nonInteractive: false }
    );
    if (!replace) {
      console.log("Skipped status line configuration.");
      return false;
    }
    settings.statusLine = { ...existingStatusLine, type: "command", command: options.statusLineCommand };
    return true;
  }

  const action = await options.prompt.choice(
    `An existing Copilot status line is configured:\n${currentCommand}\nChoose how to configure Copilot Cost.`,
    [
      { description: "Replace the existing status line with Copilot Cost.", value: "replace" },
      { description: "Decorate the existing status line with Copilot Cost using passthrough mode.", value: "decorate" },
      { description: "Leave the existing status line unchanged.", value: "skip" }
    ],
    { assumeYes: "decorate", defaultValue: "decorate", nonInteractive: "skip" }
  );

  if (action === "skip") {
    console.log("Skipped status line configuration.");
    return false;
  }

  if (action === "replace") {
    settings.statusLine = { ...existingStatusLine, type: "command", command: options.statusLineCommand };
    return true;
  }

  const decoratorPath = await ensureDecoratorLauncher({
    currentCommand,
    launcherDirectory: options.launcherDirectory,
    platform: options.platform,
    prompt: options.prompt
  });

  if (!decoratorPath) {
    console.log("Skipped status line configuration because the decorator launcher could not be installed.");
    return false;
  }

  settings.statusLine = {
    ...existingStatusLine,
    type: "command",
    command: makeStatusLineCommand(options.platform, decoratorPath)
  };
  return true;
}

async function ensureDecoratorLauncher({ currentCommand, launcherDirectory, platform, prompt }) {
  const launcherPath = path.join(launcherDirectory, platform === "windows" ? "statusline.cmd" : "statusline.sh");
  const decoratorPath = path.join(launcherDirectory, platform === "windows" ? "statusline-decorator.cmd" : "statusline-decorator.sh");
  const content = platform === "windows"
    ? windowsDecoratorContent(launcherPath, currentCommand)
    : posixDecoratorContent(launcherPath, currentCommand);

  const available = await writeGeneratedFile(decoratorPath, content, prompt, platform === "posix");
  return available ? decoratorPath : undefined;
}

function windowsDecoratorContent(launcherPath, currentCommand) {
  return `@echo off
rem ${generatedMarker}
setlocal
set "COPILOT_COST_STATUSLINE_PASSTHROUGH=${escapeBatchSetValue(currentCommand)}"
set "COPILOT_COST_STATUSLINE_MODE=decorate"
call "${escapeBatchSetValue(launcherPath)}" %*
`;
}

function posixDecoratorContent(launcherPath, currentCommand) {
  return `#!/usr/bin/env sh
# ${generatedMarker}
COPILOT_COST_STATUSLINE_PASSTHROUGH=${singleQuote(currentCommand)}
export COPILOT_COST_STATUSLINE_PASSTHROUGH
COPILOT_COST_STATUSLINE_MODE=decorate
export COPILOT_COST_STATUSLINE_MODE
exec sh ${singleQuote(launcherPath)} "$@"
`;
}

function makeStatusLineCommand(platform, launcherPath) {
  if (platform === "windows") {
    return launcherPath;
  }
  return `sh ${doubleQuote(launcherPath)}`;
}

function isCopilotCostStatusLine(command) {
  return /copilot-cli-cost/i.test(command) && /statusline/i.test(command);
}

function isPlainObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function writeSettings(settingsPath, settings, existed) {
  fs.mkdirSync(path.dirname(settingsPath), { recursive: true });

  if (existed) {
    const backupPath = `${settingsPath}.bak-${new Date().toISOString().replace(/[:.]/g, "-")}`;
    fs.copyFileSync(settingsPath, backupPath);
    console.log(`Backed up existing Copilot settings to ${backupPath}`);
  }

  const tempPath = `${settingsPath}.${process.pid}.tmp`;
  fs.writeFileSync(tempPath, `${JSON.stringify(settings, null, 2)}\n`);
  fs.renameSync(tempPath, settingsPath);
}

function createPrompter(args) {
  let readlineInterface;

  async function getReadlineInterface() {
    if (!process.stdin.isTTY || !process.stdout.isTTY) {
      return undefined;
    }
    readlineInterface ??= readline.createInterface({ input: process.stdin, output: process.stdout });
    return readlineInterface;
  }

  async function confirm(message, { assumeYes, defaultValue, nonInteractive }) {
    if (args.yes) {
      return assumeYes;
    }

    const rl = await getReadlineInterface();
    if (!rl) {
      console.log(`${message} ${nonInteractive ? "Continuing." : "Skipping because this installer is not running interactively."}`);
      return nonInteractive;
    }

    const suffix = defaultValue ? "Y/n" : "y/N";
    const answer = (await rl.question(`${message} [${suffix}] `)).trim().toLowerCase();
    if (!answer) {
      return defaultValue;
    }
    return answer === "y" || answer === "yes";
  }

  async function choice(message, choices, { assumeYes, defaultValue, nonInteractive }) {
    if (args.yes) {
      return assumeYes;
    }

    const rl = await getReadlineInterface();
    if (!rl) {
      console.log(`${message}\nSkipping because this installer is not running interactively.`);
      return nonInteractive;
    }

    const labels = choices
      .map((choiceOption, index) => `${index + 1}. ${choiceOption.description}`)
      .join("\n");
    const defaultIndex = choices.findIndex((choiceOption) => choiceOption.value === defaultValue) + 1;

    while (true) {
      const answer = (await rl.question(`${message}\n${labels}\nChoose 1-${choices.length} [${defaultIndex}]: `)).trim();
      if (!answer) {
        return defaultValue;
      }
      const selected = Number(answer);
      if (Number.isInteger(selected) && selected >= 1 && selected <= choices.length) {
        return choices[selected - 1].value;
      }
      const named = choices.find((choiceOption) => choiceOption.value.toLowerCase() === answer.toLowerCase());
      if (named) {
        return named.value;
      }
    }
  }

  process.on("exit", () => {
    readlineInterface?.close();
  });

  return { choice, confirm };
}

function escapeBatchSetValue(value) {
  if (/[\r\n]/.test(value)) {
    throw new Error("Status line commands cannot contain newlines.");
  }
  return value.replaceAll("%", "%%");
}

function singleQuote(value) {
  if (/[\r\n]/.test(value)) {
    throw new Error("Status line commands cannot contain newlines.");
  }
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function doubleQuote(value) {
  if (/[\r\n]/.test(value)) {
    throw new Error("Status line commands cannot contain newlines.");
  }
  return `"${value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"").replaceAll("$", "\\$").replaceAll("`", "\\`")}"`;
}
